const data = [
  {
    id: 1,
    name: "Dr.John Doe",
    specialist: "General Practitioner",
    experience: "5 years",
    rate: "3",
    location: "Raipur",
  },
  {
    id: 2,
    name: "Dr.Ekansh Gupta",
    specialist: "Cardiologists",
    experience: "6 years",
    rate: "5",
    location: "Bangalore",
  },
  {
    id: 3,
    name: "Dr.Rajesh Kumar",
    specialist: "Gastroenterologists",
    experience: "8 years",
    rate: "5",
    location: "Bilaspur",
  },
  {
    id: 4,
    name: "Dr.Amar",
    specialist: "General Practitioner",
    experience: "8 years",
    rate: "4",
    location: "Bilaspur",
  },
  {
    id: 5,
    name: "Dr.Shivam",
    specialist: "Allergists/Immunologists",
    experience: "8 years",
    rate: "5",
    location: "Bilaspur",
  },
  {
    id: 6,
    name: "Dr.Ravi Patel",
    specialist: "Neurologists",
    experience: "8 years",
    rate: "3",
    location: "Bilaspur",
  },
  {
    id: 7,
    name: "Dr.Shiv.Kumar",
    specialist: "Neurologists",
    experience: "8 years",
    rate: "2",
    location: "Jabalpur",
  },
  {
    id: 8,
    name: "Dr.Rajesh Kumar",
    specialist: "Gastroenterologists",
    experience: "8 years",
    rate: "4",
    location: "Mumbai",
  },
  {
    id: 9,
    name: "Dr.Amar",
    specialist: "Allergists/Immunologists",
    experience: "8 years",
    rate: "5",
    location: "Delhi",
  },
  {
    id: 10,
    name: "Dr.Abishek",
    specialist: "Gastroenterologists",
    experience: "8 years",
    rate: "4",
    location: "Mumbai",
  },
  {
    id: 11,
    name: "Dr.Abishek",
    specialist: "Allergists/Immunologists",
    experience: "8 years",
    rate: "3",
    location: "jaipur",
  },
  {
    id: 12,
    name: "Dr.Shivani",
    specialist: "Gastroenterologists",
    experience: "8 years",
    rate: "4",
    location: "Bhopal",
  },
  {
    id: 13,
    name: "Dr.Mukesh",
    specialist: "Gastroenterologists",
    experience: "8 years",
    rate: "5",
    location: "Raipur",
  },
  {
    id: 14,
    name: "Dr.Rupendra",
    specialist: "Allergists/Immunologists",
    experience: "8 years",
    rate: "3",
    location: "Delhi",
  },
  {
    id: 15,
    name: "Dr.Ravi",
    specialist: "Cardiologists",
    experience: "8 years",
    rate: "5",
    location: "Bilaspur",
  },
  {
    id: 16,
    name: "Dr.Praveen",
    specialist: "Cardiologists",
    experience: "8 years",
    rate: "5",
    location: "Bilaspur",
  },
  {
    id: 17,
    name: "Dr.Puja",
    specialist: "Neurologists",
    experience: "8 years",
    rate: "5",
    location: "Bilaspur",
  },
  {
    id: 18,
    name: "Dr.Puja",
    specialist: "Cardiologists",
    experience: "8 years",
    rate: "5",
    location: "Bilaspur",
  },
  {
    id: 19,
    name: "Dr.Tina",
    specialist: "Gastroenterologists",
    experience: "8 years",
    rate: "4",
    location: "Amritsar",
  },
  {
    id: 20,
    name: "Dr.Poonam",
    specialist: "Hematologists",
    experience: "8 years",
    rate: "5",
    location: "Raipur",
  },
  {
    id: 21,
    name: "Dr.Rajesh",
    specialist: "Hematologists",
    experience: "8 years",
    rate: "5",
    location: "Bangalore",
  },
];
export default data;
